### ISSUE TITLE
Defining recursion behavior for insert/update

### ISSUE THREAD

**Issue by Arithmomaniac** [relativitydev/Gravity#106]
We have well-defined recursion behavior for Get (can specify) and Delete (delete recursively). But what about Insert and Update?

Here is a partial proposal> "?"s mean we need to make a choice.

- Insert
  - File: Upload
  - Single/MultiObject
    - New: insert recursively
    - Update: ?
      - Use only ArtifactIDs (Depth: None)
      - Control Depth via Insert parameter (None, LevelOne, infinite)
      - Control Depth via DTO property
  - Child Object: new; insert recursively
- Update
  - File: ?
    - New: Insert
    - Delete: Clear
    - Update: ?
      - Would we upload new version if Depth is None?
      - Do we even know how to detect changes?
  - Single/Multi/Child Object:
    - New: Create
    - Updated:
      - Use only ArtifactIDs (Depth: None)
      - Control Depth via Update parameter (None, LevelOne, infinite)
      - Control Depth via DTO property
  - Child Object:
    - Missing from list: ?
      - Delete object entirely?
      - Control by recursion level if missing from list?

**Comment by Arithmomaniac** [comment]
I had a talk with a couple of people at @Milyli, and they said that they would prefer that _all_ recursive operations are explicit, using the same recursion flag we use for Get:

- Insert
  - For a Single/Multi/Child object, inserting objects past the None/First recursion level would throw an exception (we could validate this before attempting to insert)
- Delete
  - Throw exception if there are child objects past the current level of recursion control that would need to be recursively deleted
- Update
  - Ignore updates past the recursion level
  - Throw exception for inserts past the recursion level.

The thinking is that recursive operations should always be available, but never implicit (maybe you meant to assign an ArtifactID to that "new" object, for example.)

**Comment by Arithmomaniac** [comment]
Re: file fields, once we have our own response object as per #102, we can include a hidden "Untouched" field that would not be present if the response object is modified or created by the user. Then we can choose to ignore the file if it is untouched,

**Comment by mrobustelli** [comment]
Delete is done, @Arithmomaniac is working on insert, and update should be done by milestone
