### ISSUE TITLE
Need Code of Conduct

### ISSUE THREAD

**Issue by mrobustelli** [relativitydev/Gravity#110]

**Comment by mrobustelli** [comment]
@Arithmomaniac @hhristov-tsd @ggachevski Please take a look at https://github.com/relativitydev/Gravity/wiki and the pages I put up.  A first pass to build on for sure.  If there is anything else you want me to include before I close this issue, please let me know. Thanks.

**Comment by Arithmomaniac** [comment]
@mrobustelli was that comment for #111?

**Comment by mrobustelli** [comment]
added in 53275bdc3d758865f5044957dcb056bb10c9b418
