### ISSUE TITLE
Need Coding Standards

### ISSUE THREAD

**Issue by mrobustelli** [relativitydev/Gravity#111]

**Comment by Arithmomaniac** [comment]
See #18

**Comment by mrobustelli** [comment]
@Arithmomaniac @hhristov-tsd @ggachevski Please take a look at https://github.com/relativitydev/Gravity/wiki and the pages I put up. A first pass to build on for sure. If there is anything else you want me to include before I close this issue, please let me know. Thanks.

**Comment by mrobustelli** [comment]
@Arithmomaniac has opened some issues around the Coding Standards but I think we are good here.  Closing this issue out for now.
