### ISSUE TITLE
Redirect old Gravity package from TSD services to Relativity Dev

### ISSUE THREAD

**Issue by mrobustelli** [relativitydev/Gravity#112]

**Comment by mrobustelli** [comment]
TSD having some issues around the email account, should be handled by next week 9/21

**Comment by mrobustelli** [comment]
@hhristov-tsd @ggachevski Any luck around this, I would really like to close this milestone out on Wed and update some of the images for the presentation. I also need a bit of time to publish the nuget packages for the latest release.

**Comment by hhristov-tsd** [comment]
We have discussed this over with German and decided to unlist the old TSD Services Gravity package from NuGet, as he aims to eventually delete the old problematic NuGet account as well. We have confirmed here on our side that the old one is not showing up in any NuGet search (nuget.org & VS)
