### ISSUE TITLE
Unit Tests for Delete, Insert, Update where they do not exist for RSAPI.

### ISSUE THREAD

**Issue by mrobustelli** [relativitydev/Gravity#113]

**Comment by aarongilbert123** [comment]
Finish Unit Tests for Insert_FileField(), Update_ChildObject_UpdateInsertNewRemove_WithRecursion(), 
Update_FileField_Add(), Update_FileField_Remove(), Update_FileField_Modify(), Update_MultipleObject_InsertNewWithUpdatePropertyRecursion() and Update_SingleObject_InsertNewWithUpdatePropertyRecursion().

**Comment by aarongilbert123** [comment]
Done here a4874bcd88a50f126070396d72c4dc336461c5e3
