### ISSUE TITLE
Implement DBContext Helper usage for SQLDao

### ISSUE THREAD

**Issue by hhristov-tsd** [relativitydev/Gravity#133]
As discussed a couple of times, DBContext instance creation is being deprecated. So we must use the DBContext Helper from the RelativityDev - https://github.com/relativitydev/dbcontext-helper.

As of now, I have tried using the latest NuGet package of the Helper (2.0.0.2), but I was getting an error when executing a statement as reader. As I could not find that latest version on GitHub and try downloading the code to contribute, I am stuck on this one.

For now, any testing on SQL stuff can be done by linking the kCura.Crypto.dll to the Gravity project. If someone does not have the .dll or struggles finding it, please, let me know and I can send it over.

@mrobustelli - Mark, I could need some help here, but I am guessing that it is not so urgent.

**Comment by mrobustelli** [comment]
I completed this in 202cb87a4dbb9e96f79e927cb9684520b136dac2
