### ISSUE TITLE
Supporting multiple .NET Framework versions / later versions of Relativity

### ISSUE THREAD

**Issue by Arithmomaniac** [relativitydev/Gravity#15]
Gravity is currently a .NET 4.5.x project. The DLLs for Relativity 9.5.169 and onwards require .NET 4.6.2.

If we want to support later versions of the Relativity client libraries, we will need Gravity to have a target version of .NET 4.6.2 as well. If we don't want to remove functionality for older DLLs, we will need to [multi-target](https://shazwazza.com/post/multi-targeting-a-single-net-project-to-build-for-different-framework-versions/).

**Comment by mrobustelli** [comment]
Definitely think we need to discuss this sooner rather than later.  Will make sure we address at next meeting.

**Comment by Arithmomaniac** [comment]
2017-12-13 meeting: Defer until there are real breaking changes in new versions of Relativity or until we have a CI setup that could automate this somewhat.

**Comment by Arithmomaniac** [comment]
If we migrate Gravity's csproj to the new VS2017 format, you can get multitargeting on a single build. More on that [here](https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/) and [here](https://weblog.west-wind.com/posts/2017/Jun/22/MultiTargeting-and-Porting-a-NET-Library-to-NET-Core-20). 

In this case, your csproj file would start out similar to the following:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net451;net462</TargetFrameworks>
    <AssemblyName>MyAssembly</AssemblyName>
    <RootNamespace>MyAssembly</RootNamespace>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net451'">
    <PackageReference Include="Relativity.Api" Version="[9.5.89.76,9.5.162.111]" />
    <PackageReference Include="Relativity.ObjectManager" Version="[9.5.89.76,9.5.162.111]" />
    <PackageReference Include="Relativity.Other" Version="[9.5.89.76,9.5.162.111]" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <PackageReference Include="Relativity.Api" Version="9.5.89.76" />
    <PackageReference Include="Relativity.ObjectManager" Version="9.5.89.76" />
    <PackageReference Include="Relativity.Other" Version="9.5.89.76" />
  </ItemGroup>
</Project>
```
