### ISSUE TITLE
Add "topics" to project description

### ISSUE THREAD

**Issue by Arithmomaniac** [relativitydev/Gravity#17]
i.e. the things described [here](https://github.com/blog/2309-introducing-topics).

I think we should have the tag "relativity", at a minimum.

**Comment by mrobustelli** [comment]
I think this is a good idea, we should discuss which labels make sense.  The relativitydev.github.io kind of helps with this, but for general Github searching I think it will help for sure.

**Comment by mrobustelli** [comment]
Added relativity orm orm-framework devex relativitydevelopment relativity-orm

**Comment by Arithmomaniac** [comment]
Thanks!
I'd drop the last four. "DevEx" could be anything, and the other three are compounds.

**Comment by mrobustelli** [comment]
Took Avi's advice.  also added "dotnet" and "csharp"  tags do not allow .net or c#
