### ISSUE TITLE
SQL Dao/Provider

### ISSUE THREAD

**Issue by ggachevski** [relativitydev/Gravity#24]
We have been needing this on our side and we are currently in testing phase. You will be able to get your RDO via auto-generated SQL calls which provide an increase in efficiency and eliminate the Audit log burden (that may be generated by a frequent agent that does something in the background).

Initial tests show a ten-fold increase in efficiency and speed. :) We will be able to merge very soon.

**Comment by Arithmomaniac** [comment]
We have many projects where using SQL is not feasible. This should be a separate provider, not to replace RSAPI.

**Comment by ggachevski** [comment]
Absolutely, it is a separate implementation. The caller will decide which implementation they will use. It is a serious decision which isdriven by the corresponding needs at hand.

The use of the SQL implementation is tricky and risky, so it needs to be used with caution. I say this mostly from legal perspective, because everything is audited in Relativity and the SQL implementation bypasses that. Almost surely, you will not want to do Delete or Update via SQL on important objects, as it will be a violation of expected behavior.

Of course, that won't keep us from providing the functionality eventually. :)


German

________________________________

**Comment by Arithmomaniac** [comment]
@ggachevski, how is this coming along?

**Comment by ggachevski** [comment]
The tests on our app have been successful so far and I think we will be ready to push this one up to the repo in the next 1-2 weeks…

**Comment by ggachevski** [comment]
We have not confirmed this to be fully shippable quite yet. Giving it a nother couple of weeks, but should not be more than that.

**Comment by mrobustelli** [comment]
@ggachevski @hhristov-tsd @Arithmomaniac Has this been approved and merged.  Can you please close if so?

**Comment by hhristov-tsd** [comment]
I had it up in SqlDao branch a while ago and asked if someone wants any improvements on it or etc. I have fired a PR, which any of you guys can have a look at. It persists of the SqlDao and Sql Get only. I have added some really basic tests to it, which anyone of you can run to see how it works.

While/If testing, you will need to add the kCura.Crypto.dll to the Test project, as currently the DBContext Helper is yet to be implemented.

**Comment by Arithmomaniac** [comment]
Get operations added by #132

**Comment by mrobustelli** [comment]
Closing this issue.
