### ISSUE TITLE
Re-Architect for Testability

### ISSUE THREAD

**Issue by abilson** [relativitydev/Gravity#3]
The architecture of the RSAPI repositories does not allow them to be mocked. As the Gravity framework matures, a comprehensive set of unit tests will be a must for developers to contribute without breaking existing functionality. Therefore, an architecture that doesn't abstract the repositories discourages community contribution. If these repositories are separated from the framework implementation, however, unit tests are simple to implement and contributions more likely.

My architectural solution is as follows:

Inside the RsapiDao object constructor, instantiate the RsapiClient proxy and assign the supported respositories to a public property called repos. A RepoGroup object that takes an IRSAPIClient implementation and assigns the individual repos in the constructor may be best. For example:

```
class RepoGroup
{
  public RDORepository RDO;
  RepoGroup(IRSAPIClient client)
{
  this.RDO = client.repositories.RDO;
  // further supported repositories here
}
}

class RsapiDao
{
    public RepoGroup repos;
    public IRSSAPIClient client;

   RsapiDao(IHelper helper)
{
  this.client = GetProxy(helper);
  this.repo = new RepoGroup();
}
}
```

It's necessary for the repos property on the RsapiDao to be public because, when unit testing, this property must be replaceable with a mock. It may be worthwhile to indicate this property isn't intended for direct use with a combination of code comments and naming. A property with one or two underscores indicates private in Python ```__repos```.

When this architecture exists, the repos property may be used in place of the full proxy signature. For further abstraction, logic-intensive operations may have the necessary repo(s) passed via their arguments. For example:

```
public GetRelativityObject(int artifactID)
{
var rdo = this.GetRDO(artifactID, this.repos.RDO);
}
```

Thankfully, this architecture is only necessary for the RSAPI. If or when we decide to include additional services (such as a RestDao or DBContextDao) only this Dao will require this extra step.

Performance Note: It may be worthwhile to lazy load the assignment of the rsapi repositories to the RepoGroup object. I don't know what the performance hit may be, but most apps won't need all repos and this _should_ keep uncalled repos from eating up memory.

Tech Note: The RepositoryGroup object that houses all the repositories on the RSAPIClient object instantiates them inside an internal constructor. This is the reason it cannot be mocked.

**Comment by Arithmomaniac** [comment]
Being worked in in #48 .

**Comment by Arithmomaniac** [comment]
Apparently, `IRsapiRepositoryGroup` was not one of the things that made it into #48. Removing the duplicate tag.

**Comment by Arithmomaniac** [comment]
#70 took care of this.
