### ISSUE TITLE
Test no longer run. Due to error in GetEnumerableInnerType in TypeExtesions.cs

### ISSUE THREAD

**Issue by mrobustelli** [relativitydev/Gravity#73]
Looks like commit 5246bf96cb2098126d249a68fba1c8f1faf64f62 in the Dev Branch broke the Read Tests.
Get "Sequence contains no matching element" @ line 44. when trying to execute GetChildObjectRecursively @ line 111 for the objectPropertyInfo {System.Collections.Generic.IList`1[Gravity.Test.TestClasses.GravityLevel2] GravityLevel2MultipleObjs}	System.Reflection.PropertyInfo {System.Reflection.RuntimePropertyInfo}.

@Arithmomaniac were you able to execute the test when you checked this in?

**Comment by Arithmomaniac** [comment]
I have not been doing due diligence with Integration tests while checking in. I guess this shows me 😕 
I will take a look in the morning.
