### ISSUE TITLE
What should we do with choices that do not match an enum?

### ISSUE THREAD

**Issue by Arithmomaniac** [relativitydev/Gravity#80]
What should we do when reading/querying a choice field, but the choice does not correspond to any of our choice Guid/name values?

Some options:

1. **Ignore**. We could just not add those choices to the model.
    * This is simple to implement, but would not work with updates, because we would then be overwriting the value by omitting it.
2. **Store Unmapped Values.** We could keep unmapped values in a private base property of `BaseDto`. 
    * When updating, these choices could be added to those mapped from the enum.
    * Downside is that this is hacky/brittle.
3. **Throw**. Simply throw an exception if the value cannot be mapped.
    * This is simple and does not corrupt any data, but prevents using dynamic choices.

I personally favor 3.

**Comment by Arithmomaniac** [comment]
I'm assuming 3) while working on #69.

**Comment by mrobustelli** [comment]
Sorry, I should have responded sooner but got sidetracked.  This is definitely an issue.  It is in the RSAPI too when using name.  I agree with 3) for now.  I think in the long run, we will want to come up with a better solution or at least a workaround.  It is not a huge problem but I have seen it in thinks like nested choices.   There is more to get in there on that as well, but I think we are good for now.
